# -*- coding: utf-8 -*-
"""cv lab3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKFa8Ar63GJjh34qzYdHw72dFKQa7mbR
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np


def show_comparison(original, blur3, blur5, blur7):

    plt.figure(figsize=(10,8))


    plt.subplot(2, 2, 1)
    plt.imshow(original, cmap='gray')
    plt.title('Original Grayscale Image')
    plt.axis("off")


    plt.subplot(2, 2, 2)
    plt.imshow(blur3, cmap='gray')
    plt.title('Average Filter (3x3)')
    plt.axis("off")


    plt.subplot(2, 2, 3)
    plt.imshow(blur5, cmap='gray')
    plt.title('Average Filter (5x5)')
    plt.axis("off")

    plt.subplot(2, 2, 4)
    plt.imshow(blur7, cmap='gray')
    plt.title('Average Filter (7x7)')
    plt.axis("off")

    plt.tight_layout()
    plt.show()



img = cv2.imread('/content/ex.jpg', cv2.IMREAD_GRAYSCALE)


if img is None:
    print('Error: Image not found')
else:
    kernel_3x3 = np.ones((3, 3), np.float32) / 9
    kernel_5x5 = np.ones((5, 5), np.float32) / 25
    kernel_7x7 = np.ones((7, 7), np.float32) / 49

    blur3 = cv2.filter2D(img, -1, kernel_3x3)
    blur5 = cv2.filter2D(img, -1, kernel_5x5)
    blur7 = cv2.filter2D(img, -1, kernel_7x7)

    show_comparison(img, blur3, blur5, blur7)